package es.uva.eii.ds.empresamodelpc18.interfaz_empleados.pares_vista_control.empleado_personal_almacen;

/**
 * Vista del almacen
 * 
 */
public class AlmacenVista extends javax.swing.JFrame {

    private AlmacenCtrlVista controlador;
    /**
     * Creates new form TecnicoVista
     */
    public AlmacenVista() {
        initComponents();
        controlador = new AlmacenCtrlVista(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        usuarioIdentificado = new javax.swing.JLabel();
        espacioPC = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        espacioCompo = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarioIdentificado.setText("Usuario identificado: Personal almacen");
        jPanel3.add(usuarioIdentificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        espacioPC.setText("Buscar espacio para almacenar PC");
        espacioPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espacioPCActionPerformed(evt);
            }
        });
        jPanel3.add(espacioPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 293, 71));

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        espacioCompo.setText("Buscar espacio para almacenar componentes");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(espacioCompo, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(espacioCompo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanel7.setLayout(new java.awt.GridLayout(3, 1));
        jPanel4.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void espacioPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espacioPCActionPerformed
            controlador.procesarBuscarEspacioPc();
    }//GEN-LAST:event_espacioPCActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton espacioCompo;
    private javax.swing.JButton espacioPC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel usuarioIdentificado;
    // End of variables declaration//GEN-END:variables
}
