package es.uva.eii.ds.empresamodelpc18.interfaz_empleados.pares_vista_control.empleado_personal_almacen;

import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 * Vista de espacios disponibles
 * 
 */
public final class EspaciosDisponiblesVista extends javax.swing.JFrame {
    private EspaciosDisponiblesCtrlVista controlador;

    /**
     * Constructor de vista espacios disponibles
     * @param tipos tipo de cpu
     * @param numero cantidad a buscar
     * @throws SQLException busqueda no valida
     */
    public EspaciosDisponiblesVista(String tipos,int numero) throws SQLException {
        initComponents();
        setTipo(tipos);
        setNumEspacios(numero);
        int n=1;
        if(tipos.equals("Intel")){
        n=2;
        }
        controlador = new EspaciosDisponiblesCtrlVista(this);
        controlador.procesarEspacios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        tituloBuscar = new javax.swing.JLabel();
        usuarioIdentificado = new javax.swing.JLabel();
        tipoCPU = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        numEspacio = new javax.swing.JLabel();
        numEspacios = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        errorLabel = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEspacios = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        cancelar = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jPanel3.setLayout(new java.awt.GridLayout(1, 1));

        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloBuscar.setText("Buscar espacios para almacenar PCs");
        jPanel23.add(tituloBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        usuarioIdentificado.setText("Usuario identificado: Personal almacen");
        jPanel23.add(usuarioIdentificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        tipoCPU.setText("Tipo de CPU:");
        jPanel23.add(tipoCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 100, 46));
        jPanel23.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 230, 100, 46));

        numEspacio.setText("Número de espacios:");
        jPanel23.add(numEspacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 130, 46));
        jPanel23.add(numEspacios, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 160, 46));

        jPanel3.add(jPanel23);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(3, 1));

        jPanel5.setLayout(new java.awt.GridLayout(2, 4));

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(jPanel21);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel20);

        jPanel4.add(jPanel5);

        jPanel7.setLayout(new java.awt.BorderLayout());

        tablaEspacios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seccion", "Zona", "Estanteria", "Ocupado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaEspacios);

        jPanel7.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel6, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel9, java.awt.BorderLayout.LINE_START);

        jPanel4.add(jPanel7);

        jPanel10.setLayout(new java.awt.GridLayout(2, 1));

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(374, Short.MAX_VALUE)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addComponent(cancelar))
        );

        jPanel10.add(jPanel14);

        jPanel15.setLayout(new java.awt.GridLayout(2, 1));

        jPanel17.setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel18);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel8);

        jPanel15.add(jPanel17);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel16);

        jPanel10.add(jPanel15);

        jPanel4.add(jPanel10);

        jPanel2.add(jPanel4);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        controlador.procesarCancelar();
    }//GEN-LAST:event_cancelarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel numEspacio;
    private javax.swing.JLabel numEspacios;
    private javax.swing.JTable tablaEspacios;
    private javax.swing.JLabel tipo;
    private javax.swing.JLabel tipoCPU;
    private javax.swing.JLabel tituloBuscar;
    private javax.swing.JLabel usuarioIdentificado;
    // End of variables declaration//GEN-END:variables

    /**
     * Asignar espacios
     * @param numEspacios numero de espacios
     */
    public void setNumEspacios(int numEspacios) {
        this.numEspacios.setText(String.valueOf(numEspacios));
    }
    
    /**
     * Asignar tipo de cpu
     * @param tipo tipo a asignar
     */
    public void setTipo(String tipo) {
        this.tipo.setText(tipo);
    }

    /**
     * Obtener espacios
     * @return numero de espacios
     */
    public int getNumEspacios() {
        int num = Integer.parseInt(numEspacios.getText());
        return num;
    }

    /**
     * Obtener tipo de cpu
     * @return cpu
     */
    public int getTipoCPU() {
        String tip=tipo.getText();
        int numCPU=1;
        if (tip.equals("Intel")){
            numCPU=2;
        }
        return numCPU;
    }
    
    /**
     * Actualiza la tabla de resultados
     * @param seccion numero
     * @param zona numero
     * @param estanteria numero
     * @param ocupado muestra si esta ocupado o no
     */
    public void mostrarEspaciosDisponibles(int seccion, int zona, int estanteria, String ocupado) {
        DefaultTableModel model = (DefaultTableModel) tablaEspacios.getModel();
        model.addRow(new Object[]{seccion, zona, estanteria, ocupado});
    }

    /**
     * Mensaje de error
     * @param error 
     */
    void errorMessage(String error) {
        errorLabel.setText(error);
    }


}
